### ISSUE TITLE
Create a Chat group on Slack or discord

### ISSUE THREAD

**Issue by PopeSpaceous** [rhayes2/DarkChatter#3]
This will help facilitate Flow of ideas and communication between collaborators.

**Comment by Mordax** [comment]
I suggest Gitter so that we can encourage a more open source and visible dialogue.

**Comment by MuchtarSalimov** [comment]
I have created a discord server and submitted #4 to add an invite link to the readme.

I'll include it here as well.
https://discord.gg/CUsaedN

**Comment by rhayes2** [comment]
merged
