### ISSUE TITLE
Create separate repos for iOS/Android

### ISSUE THREAD

**Issue by danielbogomazov** [rhayes2/DarkChatter#7]
It would probably be better to create separate repositories for the iOS and Android versions of the application. This will reduce bloat for anyone looking to work specifically on one version and not the other. 
An organization could be created to contain both repositories.

**Comment by danielbogomazov** [comment]
@rhayes2 I've created an organization. Could you move this repository to [here](https://github.com/DarkChatter)?

**Comment by rhayes2** [comment]
As this idea has been in development by me and had to create a bunch of kickstarter material I rather leave it here and IOS isn't an option

**Comment by AHKol** [comment]
This seems like a question of 2 repos for android IOS or just one with both versions together.

I don't know if TEC class restrictions should be relevant here.

**Comment by AHKol** [comment]
I think it might be a bad idea for @rhayes2 to unilaterally decide on this multi platform decision without any discussion.

/cc @humphd

**Comment by rhayes2** [comment]
im leaving the repo here.
